Change error messages when connecting to a vicra device over serial to accurately reflect what went wrong.
SciKit-Surgery/scikit-surgerynditracker pull request #84
Opened 2024-05-23 15:21 UTC by Larbino1

Previously, the error message printed "Tried 10 devices" (for example) even if only trying to connect to 1 named serial port. This fixes the incorrect error messages and adds new error messages for the different cases.

2024-05-23 15:54 UTC, thompson318 commented
@Larbino1 thanks for the pull request. I'm away from the office till the 28th. I'll take a look then. Sorry for the delay.

2024-05-28 10:10 UTC, thompson318 requested changes
Looks good thank you. It should certainly make more helpful error messages. It took me a while to understand the for  ..  else syntax at line 77 as I haven't seen that done before but after some googling I worked it out. 
I'd prefer to avoid the global variable for SERIAL_CONNECTION_ERRMSG. Could you include it as a local variable in the _open_logging function and change it lower case?

2024-06-04 14:56 UTC, Larbino1 commented
> Looks good thank you. It should certainly make more helpful error messages. It took me a while to understand the for .. else syntax at line 77 as I haven't seen that done before but after some googling I worked it out. I'd prefer to avoid the global variable for SERIAL_CONNECTION_ERRMSG. Could you include it as a local variable in the _open_logging function and change it lower case?

Hi, I've made that change!

2024-06-04 14:57 UTC, Larbino1 commented
Oops - pressed the wrong button (closed the pull request and reopened it)- I've made the change you requested, take a look!

2024-06-06 07:59 UTC, thompson318 approved these changes

2024-06-06 07:59 UTC, merged